#!/bin/bash
#SBATCH -J test
#SBATCH -p bme_gpu
#SBATCH -o /hpc/data/home/bme/zhangzb1/Kaggle/HAT/slurm/test.out
#SBATCH -e /hpc/data/home/bme/zhangzb1/Kaggle/HAT/slurm/test.err
#SBATCH -t 120:00:00
#SBATCH -N 1
#SBATCH -n 8
#SBATCH --gres=gpu:NVIDIAA10080GBPCIe:1


source ~/.bashrc
cd /hpc/data/home/bme/zhangzb1/Kaggle/HAT/hat
conda activate trans
nvidia-smi
python test.py -opt /hpc/data/home/bme/zhangzb1/Kaggle/HAT/options/test/test.yml