# general settings
name: train_HAT-L_SRx4_scratch_Flickr360_v6_tune
model_type: HATModel
scale: 4
num_gpu: auto
manual_seed: 3407

# dataset and data loader settings
datasets:
  train:
    name: Flickr360
    type: PairedImageDataset
    dataroot_gt: /hpc/data/home/bme/zhangzb1/Kaggle/HAT/dataset/train/HR_sub_256
    dataroot_lq: /hpc/data/home/bme/zhangzb1/Kaggle/HAT/dataset/train/LR/X4_sub64
    meta_info_file: /hpc/data/home/bme/zhangzb1/Kaggle/HAT/dataset/meta_info_256.txt
    io_backend:
      type: disk

    gt_size: 256
    use_hflip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 8
    batch_size_per_gpu: 12
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: Flickr360
    type: PairedImageDataset
    dataroot_gt: /hpc/data/home/bme/zhangzb1/Kaggle/HAT/dataset/test/HR_sub_256
    dataroot_lq: /hpc/data/home/bme/zhangzb1/Kaggle/HAT/dataset/test/LR/X4_sub_64
    io_backend:
      type: disk

# network structures
network_g:
  type: HAT
  upscale: 4
  in_chans: 3
  img_size: 64
  window_size: 16
  compress_ratio: 3
  squeeze_factor: 30
  conv_scale: 0.01
  overlap_ratio: 0.5
  img_range: 1.
  depths: [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6]
  embed_dim: 180
  num_heads: [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6]
  mlp_ratio: 2
  upsampler: 'pixelshuffle'
  resi_connection: '1conv'

# path
path:
  pretrain_network_g: /hpc/data/home/bme/zhangzb1/Kaggle/HAT/experiments/train_HAT-L_SRx4_scratch_Flickr360_v5_6464/models/net_g_55000.pth
  param_key_g: 'params_ema'
  strict_load_g: true
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: RAdam
    lr: !!float 1e-6
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [10000, 20000, 45000, 60000]
    gamma: 0.5

  total_iter: 100000
  warmup_iter: 1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean
  # perceptual_opt:
  #   type: PerceptualLoss
  #   layer_weights:
  #     'conv5_4': 1  # before relu
  #   vgg_type: vgg19
  #   use_input_norm: true
  #   range_norm: false
  #   perceptual_weight: 1.0
  #   style_weight: 0
  #   criterion: l1

# validation settings
val:
  val_freq: !!float 5e3
  save_img: false
  pbar: true

  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 4
      test_y_channel: false
    ssim:
      type: calculate_ssim
      crop_border: 4
      test_y_channel: false
    ws-psnr: # metric name, can be arbitrary
      type: calculate_psnr_ws
      crop_border: 4
      test_y_channel: false
    ws-ssim: # metric name, can be arbitrary
      type: calculate_ssim_ws
      crop_border: 4
      test_y_channel: false

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
